### ISSUE TITLE
In IE10, readyState is sometimes incorrect and inert tries to observe a document.body which is null

### ISSUE THREAD

**Issue by ryanthemanuel** [WICG/inert#131] opened 2019-08-05 15:46 UTC
In IE10, readyState is sometimes incorrect and inert tries to observe a document.body which is null.  Possibly this is similar to what is being described in #75.  

Basically, from what I can tell, https://github.com/WICG/inert/blob/master/src/inert.js#L481 is flagged incorrectly, and as a result, https://github.com/WICG/inert/blob/master/src/inert.js#L589 crashes due to document.body being null.  I see in the comment here: https://github.com/WICG/inert/blob/master/src/inert.js#L588 that this is not always needed (and is actually not in my team's particular case).  Is there a way we could expose a way to programmatically disable the document.body functionality?

**Comment by robdodson** [comment] 2019-08-06 02:37
Hey @ryanthemanuel can you tell me how you're loading the polyfill? Is it in the `<head>` or the end of the `<body>`. Is it inside of a module of any kind like AMD or a webpack bundle. Just curious about other factors that might lead to this.

**Comment by ryanthemanuel** [comment] 2019-08-06 15:19
@robdodson It's in the head and in a webpack bundle due to the legacy nature of some of the code I'm dealing with.

**Comment by ryanthemanuel** [comment] 2019-08-12 14:45
@robdodson or anyone else, any thoughts on this?

**Comment by emilyrohrbough** [comment] 2019-08-14 20:44
I'm also seeing this issue. We are seeing it when using `inert` in react code for modal accessibility. I see there is some IE specific code & IE 9 & 10 can be buggy about setting `document.readyState = interactive` at time. Would it be worth adding an IE check for complete state for IE?

**Comment by emilyrohrbough** [comment] 2020-02-04 18:41
@robdodson any more traction with this?

**Comment by robdodson** [comment] 2020-02-05 23:50
I'll see if @alice and I can chat about it this week. Sorry for the lag.

**Comment by alice** [comment] 2020-02-06 03:44
Just making sure I understand, the problem is that on [line 483](https://github.com/WICG/inert/blob/master/src/inert.js#L483): 

```js
    if (document.readyState === 'loading') {
```

... this check often fails spuriously in IE? 

Is the `readyState` some other non-ready value in those cases?

**Comment by robdodson** [comment] 2020-02-06 18:12
btw we just landed a PR (#145) which may help with this... could folks give v3.0.2 a shot to see if it resolves the issue?

**Comment by JakeChampion** [comment] 2020-02-06 19:36
Fixes it for me

**Comment by goatandsheep** [comment] 2020-08-28 20:58
@ryanthemanuel  can we close this?

**Closed** 2020-08-31 20:05 UTC

**Comment by Naglaa2030** [comment] 2021-07-24 19:39
const a=document. createElement ('p'); 
a.textContent='ffffffff';
document.body.appendChild(a);
