### ISSUE TITLE
contains() throws error if activeElement is null (IE11, others?)

### ISSUE THREAD

**Issue by LouisStAmour** [WICG/inert#64] opened 2017-07-19 18:09 UTC
I've a fix, it's just adding a null check, I'll prepare a PR later this afternoon.

**Comment by valdrinkoshi** [comment] 2017-07-19 18:40
Duplicate of https://github.com/WICG/inert/issues/62
Turns out this is a bug on `node-contains`

**Closed by valdrinkoshi** 2017-07-19 18:40 UTC
